plugin: aws_ec2

aws_access_key: AKIAQMDACKUZJO6RLT73
aws_secret_key: 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

regions:
  - ap-south-1

filters:
  instance-state-name : running
 
keyed_groups:
  - key: tags.Name
    prefix: ""
    separator: ""

hostnames:
  - private-ip-address

compose:
  ansible_host: private_ip_address
